/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** TD version	:	4.6.18154
\************************************************************/

`timescale 1ns / 1ps

module uart_rx_fifo (
	rst,
	di, clk, we,
	do, re,
	empty_flag, aempty_flag,
	full_flag, afull_flag 
);

	input rst;
	input [7:0] di;
	input clk, we;
	input re;

	output [7:0] do;
	output empty_flag, aempty_flag;
	output full_flag, afull_flag;

EG_LOGIC_FIFO #(
 	.DATA_WIDTH_W(8),
	.DATA_WIDTH_R(8),
	.DATA_DEPTH_W(1024),
	.DATA_DEPTH_R(1024),
	.ENDIAN("BIG"),
	.RESETMODE("SYNC"),
	.E(0),
	.F(1024),
	.ASYNC_RESET_RELEASE("SYNC"),
	.AE(512),
	.AF(768))
logic_fifo(
	.rst(rst),
	.di(di),
	.clkw(clk),
	.we(we),
	.csw(3'b111),
	.do(do),
	.clkr(clk),
	.re(re),
	.csr(3'b111),
	.ore(1'b0),
	.empty_flag(empty_flag),
	.aempty_flag(aempty_flag),
	.full_flag(full_flag),
	.afull_flag(afull_flag)

);

endmodule
